# Calm Aquarium (mobile-first) — iPhone想定の軽量設定
meta:
  id: "003"
  title: "Calm Aquarium (Mobile)"
  description: "小さな水槽に舞う泡と一匹の熱帯魚を、モバイルブラウザでも安定して楽しめるプリセット。"
  version: 2

layout:
  orientation: "responsive"        # 端末の縦横に自動追従
  safe_area_padding_vh: 6           # 画面端からの余白（%）
  ui_scale:
    phone: 0.92
    tablet: 1.05
    desktop: 1.12

performance:
  device_focus: "mobile-first"      # iPhone 12〜15をターゲット
  max_dpr: 2
  fps_targets:
    high: 60
    medium: 45
    low: 30
  gpu_tiers:
    high: ["A17", "Snapdragon-8g3"]
    medium: ["A15", "A16", "Snapdragon-8g1"]
    low: ["A13", "A14", "Snapdragon-7g1"]

visual_theme:
  palette:
    background: "#171c2c"
    midtone: "#263862"
    highlight: "#d6e7ff"
    accent: "#8da8ff"
  fog:
    color: "#161a27"
    near: 1.8
    far: 10.5
  vignette:
    enabled: true
    strength: 0.35
    softness: 0.45

camera:
  fov: 58
  position: [4.2, 3.0, 6.4]
  target: [0.0, 1.2, 0.0]
  near: 0.1
  far: 40
  orbit_controls:
    enabled: true
    damping: 0.1
    min_distance: 2.2
    max_distance: 8.0
    min_polar_angle: 0.18
    max_polar_angle: 2.55
    enable_pan: false
    auto_rotate:
      enabled: true
      speed: 0.04

lighting:
  hemisphere:
    sky: "#9aa7ff"
    ground: "#151629"
    intensity: 0.58
  key:
    type: "directional"
    color: "#a5b6ff"
    intensity: 0.42
    position: [2.0, 4.6, 1.0]
    cast_shadow: false
  fill:
    type: "rectArea"
    color: "#324d80"
    intensity: 0.25
    width: 3.5
    height: 2.2
    position: [-1.8, 2.0, -3.0]
  caustics:
    enabled: false                 # モバイル既定はOFF。ハイ端末でのみ許可

post_processing:
  fxaa: true
  bloom:
    enabled: true
    threshold: 0.85
    strength: 0.28
    radius: 0.6
  color_grade:
    lift_gamma_gain: [0.98, 1.04, 1.05]
    temperature: -0.1
  film_grain:
    enabled: false
  tone_mapping:
    exposure: 1.05

materials:
  water_surface:
    refraction_type: "screen-space"
    strength:
      high: 0.006
      medium: 0.004
      low: 0.002
    wobble_speed: 0.5
    wobble_amplitude: 0.015
    normal_map: "textures/water-mobile-512.ktx2"
  glass:
    ior: 1.45
    roughness: 0.05
    tint: "#1f2840"

fish:
  count: 1
  mesh: "models/angel-minimal.glb"
  scale: 0.9
  path:
    type: "spline"
    radius: 2.5
    vertical_range: [0.6, 2.2]
    speed_mps: 0.3
    idle_variation: 0.06
  animation:
    body_wave:
      enabled: true
      amplitude_deg: 4.0
      frequency_hz: 0.35
      smooth_follow_s: 0.9
    tail_fin:
      enabled: true
      amplitude_deg: 12.0
      frequency_hz: 1.2
      speed_scaling: 0.8
    dorsal_fin:
      flutter_hz: 1.6
      flutter_amp: 6.0
    breathing:
      scale_variation: 0.015
      frequency_hz: 0.16
  behavior:
    avoid_bubbles: "soft"
    steering_noise: 0.08

bubbles:
  renderer: "gpu-points"
  color: "#dfe8ff"
  base_opacity: 0.46
  alpha_softedge: true
  layers:
    - id: "near"
      count:
        high: 2160
        medium: 1440
        low: 840
      spawn_region:
        radius_xz: 1.2
        y_range: [-1.3, -0.5]
      size: [1.0, 1.6]
      lifetime: [3.4, 5.4]
      rise_speed: [0.36, 0.54]
      swirl:
        type: "sine"
        frequency: [0.6, 1.1]
        amplitude: [0.02, 0.045]
      fade_tail: 0.22
      depth_fade: 0.6
    - id: "far"
      count:
        high: 1680
        medium: 1080
        low: 576
      spawn_region:
        radius_xz: 1.7
        y_range: [-1.5, -0.8]
      size: [0.7, 1.2]
      lifetime: [4.6, 7.2]
      rise_speed: [0.28, 0.42]
      swirl:
        type: "sine"
        frequency: [0.45, 0.9]
        amplitude: [0.015, 0.03]
      fade_tail: 0.27
      depth_fade: 0.75

modes:
  order: ["cinema", "wire", "shader", "mono"]
  defaults:
    refraction: "auto"
    bloom_scale: 1.0
    monotone_strength: 0.0
    wireframe: false
  cinema:
    refraction: "auto"
    bloom_scale: 1.0
    monotone_strength: 0.0
  wire:
    wireframe: true
    refraction: 0.0
    bloom_scale: 0.3
    monotone_strength: 0.2
  shader:
    wireframe: false
    refraction: "+0.0015"
    bloom_scale: 1.15
    show_normals_debug: false
  mono:
    wireframe: false
    refraction: "-0.0015"
    bloom_scale: 0.8
    monotone_strength: 0.9
    monochrome_mode: "blue-gray"

interactions:
  tap:
    action: "cycle-mode"
    toast: true
    toast_duration_ms: 1800
  double_tap:
    action: "camera-reset"
  long_press:
    threshold_ms: 420
    action:
      type: "timescale"
      value: 0.35
      easing: "quintOut"
      blend_ms: 300
  gestures:
    pinch_zoom: true
    two_finger_pan: false

adaptation:
  preset_detection:
    high:
      min_logical_pixels: 3_000_000
      gpu_tier_hint: "A17-or-better"
    medium:
      min_logical_pixels: 1_500_000
      gpu_tier_hint: "A15-A16"
    low:
      gpu_tier_hint: "A13-A14-or-lower"
  auto_throttle:
    frame_time_threshold_ms: 22
    grace_frames: 90
    adjustments:
      - apply: "bubbles:-20%, refraction:-25%"
      - apply: "bubbles:-20%, bloom:-20%"
      - apply: "preset:low"
  url_overrides:
    bubbles: null
    refraction: null
    fish: null
    mode: null
    preset: null

ui_debug:
  enabled: false
  sections:
    bubbles:
      controls: ["count", "lifetime", "riseSpeed", "swirlFreq", "swirlAmp", "opacity"]
    refraction:
      controls: ["strength", "frequency"]
    fish:
      controls: ["speed", "tailFreq", "tailAmp", "pathRadius"]
    post:
      controls: ["bloomStrength", "exposure", "monotoneStrength"]
  ranges:
    count: [200, 4000]
    lifetime: [2.0, 8.0]
    riseSpeed: [0.15, 0.8]
    swirlFreq: [0.3, 2.0]
    swirlAmp: [0.005, 0.06]
    refraction: [0.0, 0.012]
    bloomStrength: [0.0, 1.2]
    exposure: [0.7, 1.3]
    monotoneStrength: [0.0, 1.0]

shortcuts:
  toggle_mode: "KeyM"
  toggle_gui: "KeyG"
  reset_camera: "KeyR"
  pause: "KeyP"

acceptance_criteria:
  - "モバイルLowプリセットで30fpsを安定維持（DPR<=2）"
  - "泡が奥行き差を伴って上昇し、消えるまで観察できる"
  - "魚が停止せず、体幹蛇行と尾びれの周期が自然に見える"
  - "屈折やBloomが視認性を損なわずに雰囲気を向上させる"
  - "タップでモード切替、ダブルタップでカメラリセット、長押しでスローモーション"
  - "縦横切り替えやリサイズでレイアウトが破綻しない"
  - "非表示時にRAFやリスナ、GPUリソースが解放される"

notes:
  implementation_order:
    - "ベースシーン（フォグ/ライト/カメラ）"
    - "泡GPUパーティクル実装（sin揺れ＋ソフトフェード）"
    - "魚のパス追従とボーンアニメーション"
    - "ポストプロセス（FXAA + Bloom + ColorGrade）"
    - "屈折スクリーンスペースシェーダとマスク連動"
    - "表現モードのクロスフェード切替"
    - "適応レンダリングとURLオーバーライド"
