# Calm Aquarium (mobile-first) — iPhone想定の軽量設定
meta:
  id: "003"
  title: "Calm Aquarium (Mobile)"
  description: "魚の緩やかな回遊と泡の上昇、屈折と表現モード切替を、iPhoneでも快適に体験できるモバイル特化版。"
  version: 1

targets:
  device: "mobile-first"         # iPhoneを主眼に、デスクトップは後方互換
  dpr_max: 2                     # パフォーマンス基準：DPRは2まで
  fps_target:
    high: 60
    mid: 45
    low: 30

theme:
  background: "#191925"
  foreground: "#e6e6f6"
  accent: "#9aa3ff"
  fog:
    color: "#191925"
    near: 2.0
    far: 10.0

camera:
  fov: 60
  position: [4, 3, 6]
  controls:
    orbit: true
    damping: 0.12
    enable_pan: false
    min_distance: 2.0
    max_distance: 9.0
    min_polar_angle: 0.2         # 俯角制限で“水中らしさ”を保持
    max_polar_angle: 2.6

lighting:
  hemisphere:
    skyColor: "#9aa3ff"
    groundColor: "#191925"
    intensity: 0.6
  directional:
    color: "#9aa3ff"
    intensity: 0.38
    position: [2, 4, 2]
  caustics_fake:
    enabled: false               # モバイル省コストのため既定OFF
    strength: 0.15
    speed: 0.08

post:
  fxaa: true                     # モバイルはMSAAよりFXAA推奨
  bloom:
    enabled: true
    strength: 0.25               # “さりげない”Bloom
    radius: 0.6
    threshold: 0.82
  exposure: 1.0
  monotone:
    enabled: true
    mode: "blue-gray"            # "grayscale" も選択可
    strength: 0.9                # 1.0に近いほど単色寄り
  wireframe_pass:
    enabled: true
    reduce_bloom: true           # ワイヤー時はBloomを抑える

refraction:
  enabled: true
  type: "screen-space"           # スクリーン空間UVオフセット（軽量）
  strength:                      # 端末プリセットで自動調整
    high: 0.006
    mid:  0.004
    low:  0.002
  frequency: 1.0
  normal_map:
    quality: "512"               # 512〜1024で十分
  mask_bubbles_emphasis: 0.6     # 泡周辺で屈折を強める比率

fish:
  count: 1                       # モバイル既定は1体（負荷削減）
  model: "minimal-silhouette"    # 低ポリ・シルエット重視
  path:
    type: "loose-spline"
    speed_mps: 0.28
    loop: true
    bounds_radius: 2.4
  body_wave:
    enabled: true
    frequency_hz: 0.35
    amplitude_deg: 4.0           # 体幹の微妙な蛇行
    smooth_time_s: 0.9           # 進行方向への追従スムーズ
  tail_fin:
    enabled: true
    frequency_hz: 1.0
    amplitude_deg: 10.0
    speed_scaling: true          # 速度に応じて振幅が増減
  breathing:
    enabled: true
    scale_variation: 0.015       # 1.5%の体積ゆらぎ
    frequency_hz: 0.15
  collisions:
    soft_bounds: true
    bubble_reaction: "subtle"    # 泡に対する揺らぎのみ（衝突判定なし）

bubbles:
  renderer: "points-shader"      # GPUパーティクル（Points + カスタムフラグメント）
  layers:                        # 2層で奥行き感
    - name: "near"
      count:
        high: 1800
        mid:  1200
        low:   700
      spawn:
        xz_radius: 1.2
        y_range: [-1.2, -0.6]
      size: [1.0, 1.6]           # gl_PointSize用スケール（相対）
      lifetime_s: [3.5, 5.5]
      rise_velocity_mps: [0.38, 0.55]
      swirl:
        type: "sin"              # 省コスト：sinで軽量。ハイ端末でcurlへ
        frequency: [0.6, 1.2]
        amplitude: [0.02, 0.04]
      fade_out_tail: 0.2         # ライフ終盤20%でフェード
      depth_fade: 0.6
    - name: "far"
      count:
        high: 1400
        mid:   900
        low:   500
      spawn:
        xz_radius: 1.6
        y_range: [-1.4, -0.8]
      size: [0.7, 1.2]
      lifetime_s: [4.5, 7.0]
      rise_velocity_mps: [0.28, 0.42]
      swirl:
        type: "sin"
        frequency: [0.5, 1.0]
        amplitude: [0.015, 0.03]
      fade_out_tail: 0.25
      depth_fade: 0.75
  alpha_softedge: true           # 円形ソフトエッジ
  color: "#e6e6f6"
  opacity: 0.45

modes:
  order: ["cinema", "wire", "shader", "mono"]
  cinema:
    refraction: "auto"           # プリセット依存
    bloom_scale: 1.0
    monotone_strength: 0.0
    wireframe: false
  wire:
    wireframe: true
    refraction: 0.0
    bloom_scale: 0.4
    monotone_strength: 0.15      # 軽くディサチュレート
  shader:
    wireframe: false
    refraction: "+0.0015"        # 既定に対する相対加算
    bloom_scale: 1.15
    show_normals_debug: false    # 必要時のみtrue（モバイルは既定false）
  mono:
    wireframe: false
    refraction: "-0.0015"
    bloom_scale: 0.8
    monotone_strength: 0.95
    monochrome_mode: "blue-gray" # "grayscale" / "warm-gray" など

interaction:
  tap:
    action: "cycle-mode"         # cinema → wire → shader → mono → …
    toast: true
    toast_duration_ms: 1800
  double_tap:
    action: "camera-reset"
  long_press_ms: 420
  long_press_action:
    type: "timescale"
    value: 0.35                  # スローモーション
    easing: "quintOut"
    blend_ms: 220
  gestures:
    pinch_zoom: true
    two_finger_pan: false

adaptive:
  preset_detection:
    high:
      min_logical_pixels: 3_000_000   # 例: 1125×2436相当以上
      gpu_tier_hint: "A17-or-better"
    mid:
      min_logical_pixels: 1_500_000
      gpu_tier_hint: "A15-A16"
    low:
      gpu_tier_hint: "A13-A14-or-lower"
  auto_throttle:
    frame_time_ms_threshold: 22       # しきい値超過で段階的に降格
    grace_frames: 90
    steps:
      - change: "bubbles:-20%, refraction:-25%"
      - change: "bubbles:-20%, bloom:-20%"
      - change: "preset:low"
  url_overrides:
    bubbles: null        # e.g. ?bubbles=1500
    refraction: null     # e.g. ?refraction=0.004
    fish: null           # e.g. ?fish=2
    mode: null           # e.g. ?mode=mono
    preset: null         # e.g. ?preset=low

gui:                           # デバッグ用（本番は非表示が既定）
  enabled: false
  sections:
    bubbles:
      controls: ["count", "lifetime", "riseVel", "swirlFreq", "swirlAmp", "opacity"]
    refraction:
      controls: ["strength", "frequency"]
    fish:
      controls: ["speed", "tailFreq", "tailAmp", "pathBounds"]
    post:
      controls: ["bloomStrength", "exposure", "monotoneStrength"]
  ranges:
    count: [200, 4000]
    lifetime: [2.0, 8.0]
    riseVel: [0.15, 0.8]
    swirlFreq: [0.3, 2.0]
    swirlAmp: [0.005, 0.06]
    refraction: [0.0, 0.012]
    bloomStrength: [0.0, 1.2]
    exposure: [0.7, 1.3]
    monotoneStrength: [0.0, 1.0]

shortcuts:
  toggle_mode: "KeyM"
  toggle_gui: "KeyG"
  reset_camera: "KeyR"
  pause: "KeyP"

acceptance:                    # 受け入れ基準（表示のみ。実行側は参照してQAに利用）
  - "モバイルLowプリセットで30fpsを安定維持（DPR<=2）"
  - "泡は上昇→消失が視認でき、遠近の層差が分かる"
  - "魚は停止せず、体幹蛇行と尾びれ周期が自然"
  - "屈折は過度でなく、視認性を損なわない"
  - "タップでモード切替、ダブルタップでカメラリセット、長押しでスロモ"
  - "リサイズ・回転（縦横）で破綻しない"
  - "停止時にRAF/リスナ/GPUリソースが解放される"

notes:
  implementation_order:
    - "ベース/フォグ/ライト/カメラ"
    - "泡 Points（sin横揺れ・フェード）"
    - "魚モーション（経路/尾びれ/姿勢スムーズ）"
    - "ポスト（FXAA/Bloom）"
    - "屈折（screen-space, mask連動）"
    - "表現モード（wire/shader/mono）クロスフェード"
    - "適応レンダリング＆URLオーバーライド"
